### ISSUE TITLE
DRM

### ISSUE THREAD

**Issue by cubimon** [precz/wpaana#7]
Is there any way to enable DRM? I tried `about:preferences` as url and appended `prefs.js` from my profile to `runner/preferences/prefs.js`. Still without success.

**Comment by cubimon** [comment]
I use `userChrome.css` with this content to achieve fullscreen in window
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#TabsToolbar,
#PersonalToolbar,
#BookmarksToolbar,
#MenuToolbar,
#tabbrowser-tabs,
#nav-bar,
#TabsToolbar { display: none !important; }
```
[source](https://askubuntu.com/questions/487936/how-do-i-open-fixed-window-in-firefox-like-chrome-app-mode#487954)
`userChrome.css` is probably less restrictive (F12 works, but panel is empty).
. Anyway it would be still nice to change preferences.
